### ISSUE TITLE
Support for BOXER-8253AI

### ISSUE THREAD

**Issue by TheophileBlard** [koansoftware/meta-aaeonboxer#1]
Hi! 
Me and my team are working on a Yocto distribution, and we would like to deploy it on the newest BOXER-8253AI, which fulfills our needs in terms of I/O (essentially, the dual Gbe/POE Ethernet). Is it planned to support this board  ?

All this layer seems to do is to override `tegra194` kernel device tree with a Aaeon custom `.dtb`, so I guess any Xavier-NX derived board should work with the `jetson-xavier-nx-devkit-emmc` machine ?
Do you see any blocking points that would require additional work (maybe the dual Gbe-POE? or the SATA slot?).

Thank you.

**Comment by koansoftware** [comment]
Hi @TheophileBlard 
generally speaking, any Xavier-NX derived board should work just replacing the DTB, however in the specific case of BOXER-8253AI I never tested it therefore I can't guess any blocking points. It **should** work.

**Comment by TheophileBlard** [comment]
> Hi @TheophileBlard
> generally speaking, any Xavier-NX derived board should work just replacing the DTB, however in the specific case of BOXER-8253AI I never tested it therefore I can't guess any blocking points. It **should** work.

Hi @koansoftware, thanks for the quick response.
Do you know if the .dtb of the newer boards is the same than the one on this repo ? Either way, do you have a link to where the .dtb (or the .dtc) is made available by Aaeon ?

**Comment by koansoftware** [comment]
Actually I don't know. I don't have a BOXER-8253AI here. Very likely the DTB will be slightly different. You can try asking for the sources directly to AAEON.

**Comment by TheophileBlard** [comment]
We will ask directly to AAEON then, since we would not buy the BOXER-8253AI until we are sure it is compatible with Yocto.
Anyway, if we happen to make it work, I'll make sure to give you an update !

**Comment by koansoftware** [comment]
Great. In the meantime I forwarded this issue to the AAEON technical support.

**Comment by TheophileBlard** [comment]
Hi @koansoftware !
We managed to make the BOXER-8253AI works on Yocto with a .dtb file provided by AAEON.
We followed your `.bbappend` trick which overwrite the original xavier-nx .dtb.

Do you think it's possible to create a new machine and override the `KERNEL_DEVICETREE` variable instead ?

**Comment by koansoftware** [comment]
You can't create a new machine and override the KERNEL_DEVICETREE variable because you don't have the sources for the Device Tree. AAEON is not releasing sources so far although GPLv2 obey them to do that. Ask to AAEON for the .dts
