### ISSUE TITLE
Reflashing of Boxer 8251AI

### ISSUE THREAD

**Issue by Pratikp84** [koansoftware/meta-aaeonboxer#2]
I want reflash the emmc of boxer 8251 AI. will all the steps you have provided work. I havent tried them yet because i am unsure about it as i have already tried it with the boxers documentation itself but no success. Can u please help me asap. Thankyou

**Comment by koansoftware** [comment]
@Pratikp84 please contact AAEON. We are not authorized to provide support for them.
